require (sqldf)
require (dplyr)
require (lubridate)
message("loading data...")
df <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date ='1/2/2007' or Date ='2/2/2007'", eol = "\n", sep = ";")
df <- df %>% mutate(Date = dmy_hms(paste(Date, Time, sep=" ")), Global_active_power = as.numeric(Global_active_power), Global_reactive_power = as.numeric(Global_reactive_power), Voltage = as.numeric(Voltage), Global_intensity = as.numeric(Global_intensity), Sub_metering_1 = as.numeric(Sub_metering_1),Sub_metering_2 = as.numeric(Sub_metering_2),Sub_metering_3 = as.numeric(Sub_metering_3))
message("create and saving png plot...")
par(pch=22, col="black")
png(file="plot2.png",width=480,height=480)
plot(df$Date, df$Global_active_power, type="n", main ="",xlab="", ylab = "Global Active Power (kilowatts)")
lines(df$Date, df$Global_active_power, type="l")
dev.off()
message("Done!")